### ISSUE TITLE
Configure Travis-CI to build and deploy for hosted website to improve brand trust

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/mozilla-lockbox.github.io#33]
For hosting at `lockbox.firefox.com`, Travis-CI needs to be configured to build the Jekyll-based sources into HTML, and deploy to the hosting system.

## TODO
* [ ] determine publication specifics
* [ ] setup travis-ci to build Jekyll sources into site output
* [ ] setup travis-ci to assemble site output into a tarball/zip/directory
* [ ] setup travis-ci to publish tarball/zip/directory

**Comment by linuxwolf** [comment]
deployment bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1438964
